# Site settings
name: MD RUBEL
title: MD RUBEL | Software Engineer | App Developer
description: Software engineer based in Dhaka, who specializes in building (and occasionally designing) exceptional, high-quality mobile applications and websites.
url: https://cv.mdrubel.net/
baseurl: ''
email: hello@mdrubel.net
cover: https://cv.mdrubel.net/img/og.png
logo: https://cv.mdrubel.net/img/emojis/fire.png
resume: https://cv.mdrubel.net/resume.pdf
social:
  - title: email
    url: mailto:hello@mdrubel.net
  - title: twitter
    url: https://twitter.com/MDRUBELofficial
  - title: instagram
    url: https://instagram.com/_md.rubel_
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/md-rubel
  - title: linkedin
    url: https://www.linkedin.com/in/md-rubel

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
