# Site settings
name: MD RUBEL
title: Md Rubel | Senior Software Engineer
description: Software engineer based in Dhaka, who specializes in building (and occasionally designing) exceptional, high-quality mobile applications and websites.
url: https://me.mdrubel.net/
baseurl: ''
email: hello@mdrubel.net
cover: https://me.mdrubel.net/img/og.png
logo: https://me.mdrubel.net/img/logo/logo.png
resume: https://me.mdrubel.net/resume.pdf
blog: https://tech.mdrubel.net
social:
  - title: email
    url: mailto:hello@mdrubel.net
  - title: github
    url: https://github.com/theLastOrbit
  - title: linkedin
    url: https://www.linkedin.com/in/theLastOrbit
  - title: twitter
    url: https://twitter.com/_theLastOrbit
  - title: facebook
    url: https://www.facebook.com/theLastOrbit

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
